import Image1 from '../assets/hero-image.jpg'

export const products = [
  // {
  //   id: 1,
  //   name: 'VEXOFIT',
  //   type: 'Syrup',
  //   image: Image1,
  //   composition: '',
  // },
  {
    id: 2,
    name: 'VEXOTUS',
    type: 'Syrup',
    image: Image1,
    composition: 'Each 5 ML Dextramethorphan 10 Mg + Phenylephrine 5 Mg + CPM 2 Mg',
  },
  // {
  //   id: 3,
  //   name: 'CYPVEX',
  //   type: 'Syrup',
  //   image: Image1,
  //   composition: '',
  // },
  // {
  //   id: 4,
  //   name: 'VEXO-GUT',
  //   type: 'Sachets',
  //   image: Image1,
  //   composition: '',
  // },
  {
    id: 5,
    name: 'MEROVEX 1.5',
    type: 'Injection',
    image: Image1,
    composition: 'Meropenem 1000 Mg + Sulbactum 500 Mg',
  },
  // {
  //   id: 6,
  //   name: 'GABAVEX-NT',
  //   type: 'Tablets',
  //   image: Image1,
  //   composition: '',
  // },
  {
    id: 7,
    name: 'VEXETAZ 4.5',
    type: 'Injection',
    image: Image1,
    composition: 'Piperacillin 4000 Mg + Tazobactum 500 Mg',
  },
  {
    id: 8,
    name: 'VEX-Q',
    type: 'SoftGel Capsules',
    image: Image1,
    composition: 'Co Enzyme Q10, 100 Mg + Omega 3 Fatty Acid 150 Mg + Lycopene+ L Carnitine + A to Z Multivitamins + Antioxidants',
  },
  {
    id: 9,
    name: 'VEXEZONE 1.5',
    type: 'Injection',
    image: Image1,
    composition: 'Cefaperozone 1000 Mg + Sulbactum 500 Mg',
  },
  // {
  //   id: 10,
  //   name: 'BUTACEF 1 GM',
  //   type: 'Injection',
  //   image: Image1,
  //   composition: '',
  // },
  {
    id: 11,
    name: 'NERVEX',
    type: 'Capsules',
    image: Image1,
    composition: 'Methyalcobalamin 1500 Mcg + ALA 100 Mg + Folic Acid 1.5 Mg + Pyridoxine 3 Mg',
  },
  {
    id: 12,
    name: 'NERVEX 2.5',
    type: 'I.M/I.V Injection',
    image: Image1,
    composition: 'Methyalcobalamin 2500 Mcg + Pyridoxine 100 Mg + Niacinamide 100 Mg',
  },
  {
    id: 13,
    name: 'RABIVEX-D',
    type: 'SR Capsules',
    image: Image1,
    composition: 'Rabeprazole 20 Mg + Domperidone 30 Mg',
  },
  {
    id: 14,
    name: 'RABIVEX-LS',
    type: 'SR Capsules',
    image: Image1,
    composition: 'Rabeprazole 20 Mg + Levosulpiride 75 Mg SR',
  },
  {
    id: 15,
    name: 'CALIVEX-D3',
    type: 'Tablets',
    image: Image1,
    composition: 'Calcium Citrate 1000 Mg +  Magnesium 100 Mg + Vitamin D3 200IU + Zinic 4 Mg',
  },
  {
    id: 16,
    name: 'VEX-GOLD',
    type: 'Capsules',
    image: Image1,
    composition: 'Omega 3 Fatty Acid + A to Z Multivitamins +  Antioxidants',
  },
];